spring.application.name=filmorate-test

# H2 ? ??????? ????????????? PostgreSQL
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ????????? JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# SQL initialization
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
spring.sql.init.platform=h2

# Logging
logging.level.org.springframework=INFO
logging.level.org.h2=INFO